In [16]:
df.columns

Index(['Title', 'Genre', 'Premiere', 'Runtime', 'IMDB Score', 'Language'], dtype='str')

In [14]:
df['Language'].value_counts()

Language
English                       401
Hindi                          33
Spanish                        31
French                         20
Italian                        14
Portuguese                     12
Indonesian                      9
Korean                          6
Japanese                        6
Turkish                         5
English/Spanish                 5
German                          5
Dutch                           3
Polish                          3
Marathi                         3
English/Japanese                2
Filipino                        2
Thai                            2
English/Mandarin                2
English/Hindi                   2
Malay                           1
Norwegian                       1
Swedish                         1
Spanish/Basque                  1
Spanish/Catalan                 1
English/Swedish                 1
English/Taiwanese/Mandarin      1
Thia/English                    1
Georgian                        1
Bengali                         1
Khmer/English/French            1
Tamil                           1
Spanish/English                 1
English/Korean                  1
English/Arabic                  1
English/Russian                 1
English/Akan                    1
English/Ukranian/Russian        1
Name: count, dtype: int64

In [13]:
df['Genre'].value_counts()

Genre
Documentary                             159
Drama                                    77
Comedy                                   49
Romantic comedy                          39
Thriller                                 33
                                       ...
Action-adventure                          1
Animation / Science Fiction               1
Anthology/Dark comedy                     1
Musical / Short                           1
Animation/Christmas/Comedy/Adventure      1
Name: count, Length: 115, dtype: int64

In [12]:
df.isnull().sum()

Title         0
Genre         0
Premiere      0
Runtime       0
IMDB Score    0
Language      0
dtype: int64

In [11]:
df.describe()

          Runtime  IMDB Score
count  584.000000  584.000000
mean    93.577055    6.271747
std     27.761683    0.979256
min      4.000000    2.500000
25%     86.000000    5.700000
50%     97.000000    6.350000
75%    108.000000    7.000000
max    209.000000    9.000000

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 584 entries, 0 to 583
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Title       584 non-null    str
 1   Genre       584 non-null    str
 2   Premiere    584 non-null    str
 3   Runtime     584 non-null    int64
 4   IMDB Score  584 non-null    float64
 5   Language    584 non-null    str
dtypes: float64(1), int64(1), str(4)
memory usage: 27.5 KB

In [ ]:
df.head()

<bound method NDFrame.head of                                            Title                  Genre  \
0                                Enter the Anime            Documentary
1                                    Dark Forces               Thriller
2                                        The App  Science fiction/Drama
3                                 The Open House        Horror thriller
4                                    Kaali Khuhi                Mystery
..                                           ...                    ...
579        Taylor Swift: Reputation Stadium Tour           Concert Film
580  Winter on Fire: Ukraine's Fight for Freedom            Documentary
581                      Springsteen on Broadway           One-man show
582    Emicida: AmarElo - It's All For Yesterday            Documentary
583     David Attenborough: A Life on Our Planet            Documentary

              Premiere  Runtime  IMDB Score                  Language
0       August 5, 2019       58         2.5          English/Japanese
1      August 21, 2020       81         2.6                   Spanish
2    December 26, 2019       79         2.6                   Italian
3     January 19, 2018       94         3.2                   English
4     October 30, 2020       90         3.4                     Hindi
..                 ...      ...         ...                       ...
579  December 31, 2018      125         8.4                   English
580    October 9, 2015       91         8.4  English/Ukranian/Russian
581  December 16, 2018      153         8.5                   English
582   December 8, 2020       89         8.6                Portuguese
583    October 4, 2020       83         9.0                   English

[584 rows x 6 columns]>

In [6]:
df.shape

(584, 6)

In [7]:
import pandas as pd

df=pd.read_csv("NetflixOriginals.csv",encoding="latin")
df.head()

,Title,Genre,Premiere,Runtime,IMDB Score,Language
0,Enter the Anime,Documentary,"August 5, 2019",58,2.5,English/Japanese
1,Dark Forces,Thriller,"August 21, 2020",81,2.6,Spanish
2,The App,Science fiction/Drama,"December 26, 2019",79,2.6,Italian
3,The Open House,Horror thriller,"January 19, 2018",94,3.2,English
4,Kaali Khuhi,Mystery,"October 30, 2020",90,3.4,Hindi